plugins {
    id 'java'
    id 'application'
}

group = 'ru.tianji'
version = '0.0.2'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.xerial:sqlite-jdbc:3.50.3.0'

    implementation project(':api')
    testImplementation 'org.junit.jupiter:junit-jupiter:5.13.4'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'ru.tianji.Main'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
}
subprojects {

    repositories {
        mavenCentral()
    }

}
